// src/App.vue
<template>
  <div class="min-h-screen bg-white">
    <Header />
    <Hero />
    <ValueProposition />
    <AIWithHumanity />
    <Services />
    <TechStack />
    <WhyChooseUs />
    <Testimonials />
    <FinalCTA />
    <Footer />
  </div>
</template>

<script setup lang="ts">
import Header from './components/Header.vue'
import Hero from './components/Hero.vue'
import ValueProposition from './components/ValueProposition.vue'
import AIWithHumanity from './components/AIWithHumanity.vue'
import Services from './components/Services.vue'
import TechStack from './components/TechStack.vue'
import WhyChooseUs from './components/WhyChooseUs.vue'
import Testimonials from './components/Testimonials.vue'
import FinalCTA from './components/FinalCTA.vue'
import Footer from './components/Footer.vue'
</script>

// src/app/page.tsx
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Presentation from '@/components/Presentation';
import ValueProposition from '@/components/ValueProposition';
import MissionValues from '@/components/MissionValues';
import WhyChooseUs from '@/components/WhyChooseUs';
import FinalCTA from '@/components/FinalCTA';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <div className="min-h-screen">
      <Header />
      <main>
        <Hero />
        <Presentation />
        <ValueProposition />
        <MissionValues />
        <WhyChooseUs />
        <FinalCTA />
      </main>
      <Footer />
    </div>
  );
}
