// src/components/Footer.tsx
import Link from 'next/link';

const Footer = () => {
  return (
    <footer className="bg-gray-900 text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Main Footer Content */}
        <div className="py-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {/* Company Info */}
          <div className="lg:col-span-2">
            <div className="flex items-center space-x-2 mb-4">
              <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-blue-700 rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-lg">U</span>
              </div>
              <span className="text-xl font-bold">Unio Technologies</span>
            </div>
            
            <p className="text-gray-300 mb-6 max-w-md">
              Fábrica de software impulsada por IA, guiada por personas. Creamos tecnología que conecta personas y potencia ideas.
            </p>
            
            <div className="flex space-x-4">
              <a href="#" className="text-gray-400 hover:text-blue-400 transition-colors duration-200">
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/>
                </svg>
              </a>
              
              <a href="#" className="text-gray-400 hover:text-blue-400 transition-colors duration-200">
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                </svg>
              </a>
              
              <a href="#" className="text-gray-400 hover:text-blue-400 transition-colors duration-200">
                <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.174-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.165 1.775 2.165 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.099.12.112.225.085.345-.09.375-.293 1.199-.334 1.363-.053.225-.172.271-.402.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.357-.629-2.75-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24.009 12.017 24c6.624 0 11.99-5.367 11.99-11.988C24.007 5.367 18.641.001.012.001z"/>
                </svg>
              </a>
            </div>
          </div>
          
          {/* Services */}
          <div>
            <h3 className="text-lg font-semibold mb-4">Servicios</h3>
            <ul className="space-y-2">
              <li><Link href="#" className="text-gray-300 hover:text-white transition-colors duration-200">Desarrollo Web</Link></li>
              <li><Link href="#" className="text-gray-300 hover:text-white transition-colors duration-200">Apps Móviles</Link></li>
              <li><Link href="#" className="text-gray-300 hover:text-white transition-colors duration-200">Sistemas Internos</Link></li>
              <li><Link href="#" className="text-gray-300 hover:text-white transition-colors duration-200">Consultoría IA</Link></li>
              <li><Link href="#" className="text-gray-300 hover:text-white transition-colors duration-200">Soporte 24/7</Link></li>
            </ul>
          </div>
          
          {/* Company */}
          <div>
            <h3 className="text-lg font-semibold mb-4">Empresa</h3>
            <ul className="space-y-2">
              <li><Link href="#nosotros" className="text-gray-300 hover:text-white transition-colors duration-200">Nosotros</Link></li>
              <li><Link href="#proyectos" className="text-gray-300 hover:text-white transition-colors duration-200">Proyectos</Link></li>
              <li><Link href="#" className="text-gray-300 hover:text-white transition-colors duration-200">Certificaciones</Link></li>
              <li><Link href="#" className="text-gray-300 hover:text-white transition-colors duration-200">Carreras</Link></li>
              <li><Link href="#contacto" className="text-gray-300 hover:text-white transition-colors duration-200">Contacto</Link></li>
            </ul>
          </div>
        </div>
        
        {/* Bottom Footer */}
        <div className="py-6 border-t border-gray-800">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="text-gray-400 text-sm mb-4 md:mb-0">
              © 2024 Unio Technologies. Todos los derechos reservados.
            </div>
            
            <div className="flex space-x-6 text-sm">
              <Link href="#" className="text-gray-400 hover:text-white transition-colors duration-200">
                Política de Privacidad
              </Link>
              <Link href="#" className="text-gray-400 hover:text-white transition-colors duration-200">
                Términos de Servicio
              </Link>
              <Link href="#" className="text-gray-400 hover:text-white transition-colors duration-200">
                Cookies
              </Link>
            </div>
          </div>
          
          {/* Certification Badge */}
          <div className="mt-4 pt-4 border-t border-gray-800 text-center">
            <div className="inline-flex items-center space-x-2 text-gray-400 text-sm">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
              </svg>
              <span>Certificado ISO 9001:2015 - Gestión de Calidad</span>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/Footer.vue
<template>
  <footer class="bg-neutral-900 text-white py-12 px-6">
    <div class="container mx-auto">
      <div class="grid md:grid-cols-4 gap-8 mb-8">
        <!-- Brand -->
        <div class="col-span-1">
          <div class="flex items-center space-x-3 mb-4">
            <div class="w-10 h-10 bg-primary-700 rounded-lg flex items-center justify-center">
              <span class="text-white font-bold text-xl">U</span>
            </div>
            <span class="text-2xl font-bold">UNIO</span>
          </div>
          <p class="text-neutral-400 text-sm leading-relaxed">
            Software con IA y corazón humano. Transformando ideas en realidad, un proyecto a la vez.
          </p>
        </div>

        <!-- Services -->
        <div>
          <h4 class="font-bold text-lg mb-4">Servicios</h4>
          <ul class="space-y-2 text-sm text-neutral-400">
            <li><a href="#servicios" class="hover:text-white transition-colors">Desarrollo Web</a></li>
            <li><a href="#servicios" class="hover:text-white transition-colors">Apps Móviles</a></li>
            <li><a href="#servicios" class="hover:text-white transition-colors">Machine Learning</a></li>
            <li><a href="#servicios" class="hover:text-white transition-colors">UX/UI Design</a></li>
            <li><a href="#servicios" class="hover:text-white transition-colors">Consultoría IA</a></li>
          </ul>
        </div>

        <!-- Company -->
        <div>
          <h4 class="font-bold text-lg mb-4">Empresa</h4>
          <ul class="space-y-2 text-sm text-neutral-400">
            <li><a href="#nosotros" class="hover:text-white transition-colors">Sobre nosotros</a></li>
            <li><a href="#" class="hover:text-white transition-colors">Blog</a></li>
            <li><a href="#" class="hover:text-white transition-colors">Casos de éxito</a></li>
            <li><a href="#" class="hover:text-white transition-colors">Carreras</a></li>
            <li><a href="#contacto" class="hover:text-white transition-colors">Contacto</a></li>
          </ul>
        </div>

        <!-- Newsletter -->
        <div>
          <h4 class="font-bold text-lg mb-4">Newsletter</h4>
          <p class="text-sm text-neutral-400 mb-4">
            Recibe tips, insights y novedades sobre IA y desarrollo.
          </p>
          <div class="flex">
            <input 
              type="email" 
              placeholder="tu@email.com" 
              class="flex-1 px-4 py-2 rounded-l-lg bg-neutral-800 border border-neutral-700 text-white text-sm focus:outline-none focus:border-primary-500"
            />
            <button class="px-4 py-2 bg-primary-700 rounded-r-lg hover:bg-primary-800 transition-all">
              ✓
            </button>
          </div>
        </div>
      </div>

      <!-- Bottom -->
      <div class="border-t border-neutral-800 pt-8 flex flex-col md:flex-row justify-between items-center text-sm text-neutral-400">
        <p>&copy; 2025 UNIO. Todos los derechos reservados.</p>
        <div class="flex space-x-6 mt-4 md:mt-0">
          <a href="#" class="hover:text-white transition-colors">Privacidad</a>
          <a href="#" class="hover:text-white transition-colors">Términos</a>
          <a href="#" class="hover:text-white transition-colors">Cookies</a>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
</script>
