// src/components/Header.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';

const Header = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <header className="bg-white shadow-sm border-b border-gray-100 sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          {/* Logo */}
          <div className="flex-shrink-0">
            <Link href="/" className="flex items-center space-x-2">
              <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-blue-700 rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-lg">U</span>
              </div>
              <span className="text-xl font-bold text-gray-900">Unio Technologies</span>
            </Link>
          </div>

          {/* Desktop Navigation */}
          <nav className="hidden md:flex space-x-8">
            <Link href="#inicio" className="text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium">
              Inicio
            </Link>
            <Link href="#servicios" className="text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium">
              Servicios
            </Link>
            <Link href="#nosotros" className="text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium">
              Nosotros
            </Link>
            <Link href="#proyectos" className="text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium">
              Proyectos
            </Link>
            <Link href="#contacto" className="text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium">
              Contacto
            </Link>
          </nav>

          {/* CTA Button */}
          <div className="hidden md:flex">
            <Link
              href="#contacto"
              className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition-colors duration-200 font-medium shadow-sm"
            >
              Empezar proyecto
            </Link>
          </div>

          {/* Mobile menu button */}
          <div className="md:hidden">
            <button
              onClick={() => setIsMenuOpen(!isMenuOpen)}
              className="text-gray-700 hover:text-blue-600 focus:outline-none focus:text-blue-600"
            >
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                {isMenuOpen ? (
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                ) : (
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                )}
              </svg>
            </button>
          </div>
        </div>

        {/* Mobile Navigation */}
        {isMenuOpen && (
          <div className="md:hidden">
            <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-white border-t border-gray-100">
              <Link
                href="#inicio"
                className="block px-3 py-2 text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium"
                onClick={() => setIsMenuOpen(false)}
              >
                Inicio
              </Link>
              <Link
                href="#servicios"
                className="block px-3 py-2 text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium"
                onClick={() => setIsMenuOpen(false)}
              >
                Servicios
              </Link>
              <Link
                href="#nosotros"
                className="block px-3 py-2 text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium"
                onClick={() => setIsMenuOpen(false)}
              >
                Nosotros
              </Link>
              <Link
                href="#proyectos"
                className="block px-3 py-2 text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium"
                onClick={() => setIsMenuOpen(false)}
              >
                Proyectos
              </Link>
              <Link
                href="#contacto"
                className="block px-3 py-2 text-gray-700 hover:text-blue-600 transition-colors duration-200 font-medium"
                onClick={() => setIsMenuOpen(false)}
              >
                Contacto
              </Link>
              <div className="px-3 py-2">
                <Link
                  href="#contacto"
                  className="block w-full text-center bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors duration-200 font-medium"
                  onClick={() => setIsMenuOpen(false)}
                >
                  Empezar proyecto
                </Link>
              </div>
            </div>
          </div>
        )}
      </div>
    </header>
  );
};

export default Header;

// src/components/Header.vue
<template>
  <header class="fixed top-0 left-0 right-0 z-50 bg-white/90 backdrop-blur-lg border-b border-neutral-200 shadow-sm">
    <nav class="container mx-auto px-6 py-4">
      <div class="flex items-center justify-between">
        <!-- Logo -->
        <div class="flex items-center space-x-3">
          <div class="w-10 h-10 bg-primary-700 rounded-lg flex items-center justify-center shadow-sm">
            <span class="text-white font-bold text-xl">U</span>
          </div>
          <span class="text-2xl font-bold text-primary-900">UNIO</span>
        </div>

        <!-- Desktop Menu -->
        <div class="hidden md:flex items-center space-x-8">
          <a href="#inicio" class="text-neutral-700 hover:text-primary-600 transition-colors font-medium">Inicio</a>
          <a href="#servicios" class="text-neutral-700 hover:text-primary-600 transition-colors font-medium">Servicios</a>
          <a href="#tecnologia" class="text-neutral-700 hover:text-primary-600 transition-colors font-medium">Tecnología</a>
          <a href="#nosotros" class="text-neutral-700 hover:text-primary-600 transition-colors font-medium">Nosotros</a>
          <a href="#contacto" class="px-6 py-2.5 bg-primary-700 text-white font-semibold rounded-lg hover:bg-primary-800 transition-all duration-300 shadow-sm hover:shadow-md">
            Contacto
          </a>
        </div>

        <!-- Mobile Menu Button -->
        <button 
          @click="mobileMenuOpen = !mobileMenuOpen"
          class="md:hidden text-neutral-700 focus:outline-none"
          aria-label="Toggle menu"
        >
          <svg v-if="!mobileMenuOpen" class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <svg v-else class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <!-- Mobile Menu -->
      <div 
        v-show="mobileMenuOpen"
        class="md:hidden mt-4 pb-4 space-y-4 animate-fade-in"
      >
        <a href="#inicio" class="block text-neutral-700 hover:text-primary-600 transition-colors font-medium">Inicio</a>
        <a href="#servicios" class="block text-neutral-700 hover:text-primary-600 transition-colors font-medium">Servicios</a>
        <a href="#tecnologia" class="block text-neutral-700 hover:text-primary-600 transition-colors font-medium">Tecnología</a>
        <a href="#nosotros" class="block text-neutral-700 hover:text-primary-600 transition-colors font-medium">Nosotros</a>
        <a href="#contacto" class="block px-6 py-2.5 bg-primary-700 text-white font-semibold rounded-lg text-center hover:bg-primary-800 transition-all">
          Contacto
        </a>
      </div>
    </nav>
  </header>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const mobileMenuOpen = ref(false)
</script>
