// src/components/Hero.tsx
import Link from 'next/link';
import Image from 'next/image';

const Hero = () => {
  return (
    <section id="inicio" className="relative bg-gradient-to-br from-gray-50 to-blue-50 min-h-screen flex items-center">
      {/* Background Pattern */}
      <div className="absolute inset-0 bg-grid-pattern opacity-5"></div>
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Content */}
          <div className="space-y-8">
            <div className="space-y-6">
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 leading-tight">
                <span className="block">Tecnología que</span>
                <span className="block text-blue-600">conecta personas.</span>
                <span className="block text-sm md:text-base lg:text-lg font-medium text-gray-600 mt-4">
                  Inteligencia artificial que acelera, humanos que inspiran.
                </span>
              </h1>
              
              <p className="text-lg md:text-xl text-gray-600 max-w-2xl leading-relaxed">
                En Unio creamos soluciones digitales en tiempo récord, sin perder lo más valioso: el toque humano.
              </p>
            </div>

            {/* CTA Buttons */}
            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                href="#contacto"
                className="inline-flex items-center justify-center px-8 py-4 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-all duration-200 shadow-lg hover:shadow-xl transform hover:-translate-y-1"
              >
                Construyamos tu solución
                <svg className="ml-2 w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
              </Link>
              
              <Link
                href="#proyectos"
                className="inline-flex items-center justify-center px-8 py-4 bg-white text-gray-700 font-semibold rounded-lg border-2 border-gray-200 hover:border-blue-600 hover:text-blue-600 transition-all duration-200 shadow-sm hover:shadow-md"
              >
                Conoce nuestros proyectos
                <svg className="ml-2 w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </Link>
            </div>

            {/* Stats */}
            <div className="flex flex-wrap gap-8 pt-8 border-t border-gray-200">
              <div className="text-center">
                <div className="text-2xl font-bold text-blue-600">100+</div>
                <div className="text-sm text-gray-600">Proyectos entregados</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-blue-600">ISO 9001</div>
                <div className="text-sm text-gray-600">Certificación</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-blue-600">24/7</div>
                <div className="text-sm text-gray-600">Soporte técnico</div>
              </div>
            </div>
          </div>

          {/* Hero Image */}
          <div className="relative">
            <div className="relative z-10">
              <div className="bg-white rounded-2xl shadow-2xl p-8 transform rotate-3 hover:rotate-0 transition-transform duration-300">
                <div className="space-y-4">
                  <div className="flex items-center space-x-3">
                    <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                    <div className="w-3 h-3 bg-yellow-500 rounded-full"></div>
                    <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                  </div>
                  <div className="space-y-3">
                    <div className="h-4 bg-gray-200 rounded w-3/4"></div>
                    <div className="h-4 bg-blue-200 rounded w-1/2"></div>
                    <div className="h-4 bg-gray-200 rounded w-5/6"></div>
                    <div className="h-8 bg-blue-600 rounded w-1/3"></div>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Floating Elements */}
            <div className="absolute -top-4 -right-4 w-20 h-20 bg-blue-100 rounded-full flex items-center justify-center animate-bounce">
              <svg className="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            
            <div className="absolute -bottom-4 -left-4 w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center animate-pulse">
              <svg className="w-6 h-6 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
          </div>
        </div>
      </div>
      
      {/* Scroll Indicator */}
      <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce">
        <svg className="w-6 h-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
        </svg>
      </div>
    </section>
  );
};

export default Hero;

// src/components/Hero.vue
<template>
  <section id="inicio" class="pt-32 pb-20 px-6 bg-gradient-to-br from-neutral-50 via-white to-primary-50 overflow-hidden">
    <div class="container mx-auto">
      <div class="grid lg:grid-cols-2 gap-12 items-center">
        <!-- Left Content -->
        <div class="space-y-8 animate-fade-in-up">
          <div class="inline-block px-4 py-2 bg-white rounded-lg shadow-sm border border-primary-200">
            <span class="text-primary-800 font-semibold text-sm">✨ Inteligencia Artificial con Corazón Humano</span>
          </div>
          
          <h1 class="text-5xl md:text-6xl lg:text-7xl font-bold leading-tight">
            Software que
            <span class="gradient-text"> piensa </span>
            y
            <span class="gradient-text"> siente </span>
          </h1>
          
          <p class="text-xl text-neutral-600 leading-relaxed">
            En UNIO fusionamos la potencia de la inteligencia artificial con la calidez humana. 
            Creamos software que no solo resuelve problemas, sino que entiende a las personas.
          </p>
          
          <div class="flex flex-col sm:flex-row gap-4">
            <a href="#contacto" class="btn-primary text-center">
              Comienza tu proyecto
              <span class="ml-2">→</span>
            </a>
            <a href="#servicios" class="btn-secondary text-center">
              Conoce más
            </a>
          </div>

          <!-- Stats -->
          <div class="grid grid-cols-3 gap-6 pt-8">
            <div class="text-center">
              <div class="text-3xl font-bold text-primary-700">150+</div>
              <div class="text-sm text-neutral-600 mt-1">Proyectos</div>
            </div>
            <div class="text-center">
              <div class="text-3xl font-bold text-primary-700">98%</div>
              <div class="text-sm text-neutral-600 mt-1">Satisfacción</div>
            </div>
            <div class="text-center">
              <div class="text-3xl font-bold text-primary-700">24/7</div>
              <div class="text-sm text-neutral-600 mt-1">Soporte</div>
            </div>
          </div>
        </div>

        <!-- Right Visual -->
        <div class="relative animate-fade-in">
          <div class="relative z-10">
            <!-- Main Card -->
            <div class="bg-white rounded-3xl shadow-2xl p-8 space-y-6">
              <div class="flex items-center space-x-3">
                <div class="w-12 h-12 bg-gradient-to-br from-primary-500 to-accent-500 rounded-xl flex items-center justify-center">
                  <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </div>
                <div>
                  <div class="font-semibold text-neutral-800">IA en Acción</div>
                  <div class="text-sm text-neutral-500">Procesando con empatía</div>
                </div>
              </div>
              
              <!-- Progress Bars -->
              <div class="space-y-4">
                <div>
                  <div class="flex justify-between text-sm mb-2">
                    <span class="text-neutral-700">Análisis de Datos</span>
                    <span class="text-primary-600 font-semibold">95%</span>
                  </div>
                  <div class="h-2 bg-neutral-100 rounded-full overflow-hidden">
                    <div class="h-full bg-gradient-to-r from-primary-500 to-accent-500 rounded-full animate-pulse-slow" style="width: 95%"></div>
                  </div>
                </div>
                <div>
                  <div class="flex justify-between text-sm mb-2">
                    <span class="text-neutral-700">Comprensión Humana</span>
                    <span class="text-primary-600 font-semibold">100%</span>
                  </div>
                  <div class="h-2 bg-neutral-100 rounded-full overflow-hidden">
                    <div class="h-full bg-gradient-to-r from-accent-500 to-primary-500 rounded-full" style="width: 100%"></div>
                  </div>
                </div>
                <div>
                  <div class="flex justify-between text-sm mb-2">
                    <span class="text-neutral-700">Innovación</span>
                    <span class="text-primary-600 font-semibold">98%</span>
                  </div>
                  <div class="h-2 bg-neutral-100 rounded-full overflow-hidden">
                    <div class="h-full bg-gradient-to-r from-primary-600 to-primary-700 rounded-full animate-pulse-slow" style="width: 98%"></div>
                  </div>
                </div>
              </div>

              <!-- Icons Grid -->
              <div class="grid grid-cols-4 gap-4 pt-4">
                <div class="bg-primary-50 rounded-xl p-3 text-center">
                  <div class="text-2xl mb-1">🤖</div>
                  <div class="text-xs text-neutral-600">IA</div>
                </div>
                <div class="bg-accent-50 rounded-xl p-3 text-center">
                  <div class="text-2xl mb-1">❤️</div>
                  <div class="text-xs text-neutral-600">Humano</div>
                </div>
                <div class="bg-primary-50 rounded-xl p-3 text-center">
                  <div class="text-2xl mb-1">⚡</div>
                  <div class="text-xs text-neutral-600">Rápido</div>
                </div>
                <div class="bg-accent-50 rounded-xl p-3 text-center">
                  <div class="text-2xl mb-1">🎯</div>
                  <div class="text-xs text-neutral-600">Preciso</div>
                </div>
              </div>
            </div>
          </div>

          <!-- Floating Elements -->
          <div class="absolute -top-6 -right-6 w-32 h-32 bg-accent-200/30 rounded-full blur-3xl animate-float"></div>
          <div class="absolute -bottom-6 -left-6 w-40 h-40 bg-primary-200/30 rounded-full blur-3xl animate-float" style="animation-delay: 1s"></div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
</script>
